# Generated by Django 4.0.4 on 2022-04-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_companies_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='company_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.companies'),
        ),
    ]
