# Generated by Django 4.0.4 on 2022-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_devices_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_ip',
            field=models.CharField(max_length=50, verbose_name='IP'),
        ),
    ]
