# Generated by Django 4.0.4 on 2022-05-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='Is Checked?'),
        ),
    ]
