# Generated by Django 4.0.4 on 2022-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_devices_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
    ]
