# Generated by Django 4.0.4 on 2022-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_devices_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='ssid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
