# Generated by Django 4.0.4 on 2022-06-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_devices_ssid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='device_id',
            new_name='deviceid',
        ),
    ]
